Mathematical objects
==

* *Scalars*: A scalar is just a single number
* *Vectors*: A vector is an array of numbers
* *Matrices*: A matrix is a 2-D array of numbers
* *Tensors*: An array of numbers arranged on a regular grid with a variable number of axes

In [1]:
import numpy as np

In [21]:
a = np.array([[1, 2], [2, 3], [3, 4]], dtype=np.float)
print('a:', a)
print('aT:', np.transpose(a))

a: [[ 1.  2.]
 [ 2.  3.]
 [ 3.  4.]]
aT: [[ 1.  2.  3.]
 [ 2.  3.  4.]]


In [18]:
# We can add matrices to each other, as long as they have the same shape
b = np.array([[-2, -1], [4, 5], [-4, -3]], dtype=np.float)
print('b:', b)
print('2 * a + b + 1:', 2 * a + b + 2)
# element-wise product or Hadamard product
print('a * b:', a * b)

b: [[-2. -1.]
 [ 4.  5.]
 [-4. -3.]]
2 * a + b + 1: [[  2.   5.]
 [ 10.  13.]
 [  4.   7.]]
a * b: [[ -2.  -2.]
 [  8.  15.]
 [-12. -12.]]


In [19]:
# The matrix product of matrices A and B is a third matrix C.
# In order for this product to be defined, A must have the same number of columns as B has rows.
# If A is of shape m × n and B is of shape n × p, then C is of shape m × p.
c = np.array([[1, 2, 3, 4], [4, 5, 6, 8]], dtype=np.float)
print('c:', c)
print('a dot c:', np.dot(a, c))

c: [[ 1.  2.  3.  4.]
 [ 4.  5.  6.  8.]]
a dot c: [[  9.  12.  15.  20.]
 [ 14.  19.  24.  32.]
 [ 19.  26.  33.  44.]]


In [20]:
# Matrix multiplication is not commutative (the condition AB = BA does not always hold),
# However, the dot product between two vectors is commutative: xTy = yTx.
d = np.array([[1, 2, 3, 4]], dtype=np.float)
e = np.array([[5, 6, 7, 8]], dtype=np.float)
print(np.dot(np.transpose(d), e))
print(np.dot(np.transpose(e), d))

[[  5.   6.   7.   8.]
 [ 10.  12.  14.  16.]
 [ 15.  18.  21.  24.]
 [ 20.  24.  28.  32.]]
[[  5.  10.  15.  20.]
 [  6.  12.  18.  24.]
 [  7.  14.  21.  28.]
 [  8.  16.  24.  32.]]


In [24]:
# An identity matrix is a matrix that does not change any vector when we multiply that vector by that matrix.
print(np.identity(3, dtype=np.float))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [32]:
# The matrix inverse of A is denoted as A−1, and it is defined as the matrix such that A−1A = In.
aI = np.matrix.getI(a)
print('aI:', aI)
print('aIa = In', np.matrix.dot(aI, a))

aI: [[-1.83333333 -0.33333333  1.16666667]
 [ 1.33333333  0.33333333 -0.66666667]]
aIa = In [[  1.00000000e+00   1.77635684e-15]
 [  3.33066907e-16   1.00000000e+00]]


In [37]:
# usually measure the size of vectors using a function called a *norm*.
print('norm:', np.linalg.norm(a, ord=2))

norm: 6.54675563644


Special kins of matrices and vectors
==

* *Diagonal matrices* consist mostly of zeros and have non-zero entries only along the main diagonal.
* A *symmetric matrix* is any matrix that is equal to its own transpose
* A *unit vector* is a vector with *unit norm*
* A vector **x** and a vector **y** are *orthogonal* to each other if `np.dot(np.transpose(x), y) == 0`
* If the vectors are not only *orthogonal* but also have *unit norm*, we call them *orthonormal*
* An *orthogonal matrix* is a square matrix whose rows are mutually orthonormal and whose columns are mutually orthonormal
* The *determinant* of a square matrix, denoted det(A), is a function mapping matrices to real scalars.
* The *trace operator* gives the sum of all of the diagonal entries of a matrix
* The *singular value decomposition (SVD)* provides another way to factorize a matrix, into *singular vectors* and *singular values*